name: "Publish Docker Images via Template"

permissions:
  contents: read
  id-token: write
  packages: write

on:
  workflow_dispatch:
  schedule:
    - cron: '00 05 * * *'

jobs:
  ## Ubuntu
  ubuntu-edge:
    uses: ./.github/workflows/image-template.yml
    with:
      distro: ubuntu
      release: stable
    secrets: inherit

  ubuntu-stable:
    needs: ubuntu-edge
    uses: ./.github/workflows/image-template.yml
    with:
      distro: ubuntu
      release: stable
    secrets: inherit

  ## Alpine
  alpine-edge:
    uses: ./.github/workflows/image-template.yml
    with:
      distro: alpine
      release: edge
    secrets: inherit

  alpine-stable:
    needs: alpine-edge
    uses: ./.github/workflows/image-template.yml
    with:
      distro: alpine
      release: stable
      latest: true
    secrets: inherit
