name: "Publish Docker Images via Template"

permissions:
  contents: read
  id-token: write
  packages: write

on:
  workflow_dispatch:
  schedule:
    - cron: '00 05 * * *'

jobs:
    ## Ubuntu
    github-ubuntu-edge:
      uses: ./.github/workflows/image-template.yml
      with:
          distro: ubuntu
          release: edge
      secrets: inherit

    github-ubuntu-stable:
      uses: ./.github/workflows/image-template.yml
      with:
          distro: ubuntu
          release: stable
      secrets: inherit

    ## Alpine
    github-alpine-edge:
      uses: ./.github/workflows/image-template.yml
      with:
          distro: alpine
          release: edge
      secrets: inherit

    github-alpine-stable:
      uses: ./.github/workflows/image-template.yml
      with:
          distro: alpine
          release: stable
          latest: true
      secrets: inherit
