# for Privoxy
name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      distro:
        description: "One of alpine or ubuntu"
        required: true
        type: string
        default: alpine
      release:
        description: "One of stable or edge"
        required: true
        type: string
        default: stable
      latest:
          description: "Set 'latest' tag"
          required: false
          type: boolean
          default: false

  workflow_call:
    inputs:
      distro:
        description: "One of alpine or ubuntu"
        required: true
        type: string
      release:
        description: "One of stable or edge"
        required: true
        type: string
      latest:
          description: "Set 'latest' tag"
          required: false
          type: boolean
          default: false

env:
  # name of image
  IMAGE: privoxy
  # gh or docker registry
  REGISTRY: ghcr.io
  # build context
  CONTEXT: .
  # image distro
  DISTRO: ${{ inputs.distro }}
  # image release
  RELEASE: ${{ inputs.release }}
  # build arguments to be created in first step
  BUILD_ARGS: ''
  IMAGE_PATHS: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: "Set build arguments"
        id: "set-buildargs"
        env:
          ALPINE_VER: ${{ vars.ALPINE_VER }}
          UBUNTU_VER: ${{ vars.UBUNTU_VER }}
          PRIVOXY_STABLE: ${{ vars.PRIVOXY_STABLE }}
        shell: "bash"
        run: |
          {
            echo 'BUILD_ARGS<<EOF'
            [ "${DISTRO}" == alpine ] && echo \"ALPINE_VER=${ALPINE_VER}\" || echo \"UBUNTU_VER=${UBUNTU_VER}\"
            [ "${RELEASE}" == stable ] && echo \"PRIVOXY_VER=${PRIVOXY_STABLE}\" || echo \"PRIVOXY_VER=edge\"
            echo EOF
          } >> $GITHUB_ENV

      - name: "Set image paths to publish"
        id: "set-image-paths"
        env:
          BRANCH: ${{ github.ref_name }}
        shell: "bash"
        run: |
          {
            echo 'IMAGE_PATHS<<EOF'
            [ "${BRANCH}" == main ] && echo tmknight88/${IMAGE}
            echo ${REGISTRY}/tmknight/${IMAGE}
            echo EOF
          } >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup QEMU for multi-arch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
          cache-image: false

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3


      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: ${{ env.CONTEXT }}
          platforms: linux/amd64,linux/arm64
          file: docker/${{ env.DISTRO }}/${{ env.IMAGE }}.dockerfile
          build-args: ${{ env.BUILD_ARGS }}
          tags: privoxy

